# Chord and sentiments (Information Sheet)

## Basic information about this study

The study aims to investigate the link between chords and emotions. It should take approximately 12 minutes or less to complete.

## What happens if I take part?
You will hear a short chord sequence where you will be asked to focus on the last chord of the sequence and characterise the expression or feeling it conveys using a offered terms or a term of your own. You will also complete some questionnaires asking for basic demographic information as well as some more specific information about your expertise and preferences in music. 

## Participation
Participation is entirely voluntary, and you do not have to take part. 

## What are the benefits?
You will be making a valuable contribution to our understanding of how music is able to express emotions.

## What are the risks?
There are no foreseeable risks involved in participating in this study. This experiment requires you to listen sounds from your audio device. Make sure you adjust volume to avoid any discomfort. Before the experiment there will be a sound level test to check your audio is at a comfortable level. 

## What if something goes wrong? 
It is unlikely that anything will go wrong, but if you feel it has, please contact Tuomas Eerola <a href="mailto:tuomas.eerola@durham.ac.uk">tuomas.eerola@durham.ac.uk</A>.

## What if I change my mind during the study or after the study is complete?

You can stop at any point during the study by closing the browser window. If, having completed the study, you change your mind and wish to withdraw your data, simply email the researchers using the email address <a href="mailto:tuomas.eerola@durham.ac.uk">tuomas.eerola@durham.ac.uk</A>. All data provided will be anonymised, they will not be available to anyone outside the researchers listed above and cannot be traced back to your identity. All data published will be entirely anonymous and unidentifiable. The responsibility for this survey rests entirely with the researchers listed above. 

## Data Protection Information 
No personal data will be shared. Anonymised (i.e. not identifiable) data may be used in publications, reports, presentations, and other research outputs. All anonymised research data and records needed to validate the research findings will be stored for 10 years after the publication of the results, as 10 years is the standard under Durham University’s data management policy.

Thank you in advance for your participation! 

